2014-03-16 20:22:42,089 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:22:42,089 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:22:42,402 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:22:42,403 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:22:42,403 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:22:42,474 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:24:26,725 [ERROR] django.request: Internal Server Error: /articles/all
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/gk/django_test/django_test/urls.py", line 2, in <module>
    from article.views import HelloTemplate
  File "/home/gk/django_test/article/views.py", line 110
    logr.debug(srch_text)
   ^
IndentationError: unexpected indent
2014-03-16 20:24:44,995 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:24:45,087 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:24:45,339 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:08,478 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:08,654 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:08,842 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:09,442 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:09,478 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:09,657 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:25:09,924 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 109, in search_titles
    logr.debug(srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:12,698 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:12,723 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:13,069 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:13,069 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:37,688 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:37,845 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,005 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,362 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,459 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,532 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,790 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
2014-03-16 20:26:38,843 [ERROR] django.request: Internal Server Error: /articles/search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gk/django_test/article/views.py", line 110, in search_titles
    articles = Article.objects.filter(title__contains=srch_text)
NameError: global name 'srch_text' is not defined
